content: 
  - name: blog
    label: Blog
    type: collection
    path: 'src/blog'
    view: 
      fields: [ title, date, draft]
    fields: 
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: date
        label: Date
        type: date
      - name: tags
        label: Tags
        type: string
        list: true
        fields: 
          - name: tag
            label: Tag
            type: string
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text
  - name: notes
    label: Notes
    type: collection
    path: 'src/notes'
    view: 
      fields: [ title, date, draft]
    fields: 
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: date
        label: Date
        type: date
      - name: tags
        label: Tags
        type: string
        list: true
        fields: 
          - name: tag
            label: Tag
            type: string
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text
  - name: gifts
    label: Gifts
    type: file
    path: 'src/gifts.md'
    fields: 
      - name: layout
        label: Layout
        type: select
        options: 
          values:
            - value: 'layouts/single-page.njk'
              label: Single Page
        default: 'layouts/single-page.njk'
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
      - name: body
        label: Body
        type: rich-text